correction/correction/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('institute/', include('institute.urls')),
    path('frontoffice/', include('frontoffice.urls')),
    path('leave/', include('leave.urls')),
    path('library/', include('library.urls')),
    path('idcard/', include('idcard.urls')),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('admitcard/', include('admitcard.urls')),
    path('certificate/', include('certificate.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

correction/leave/urls.py
from django.urls import path
from .views import leavetype, leave

app_name = 'leave'

urlpatterns = [
    # leave
    path('leaves/', leave.AllLeaveView.as_view(), name="leaves"),
    path('leave/<int:pk>', leave.DetailLeaveView.as_view(), name="leave"),
    path('add_leave/', leave.AddLeaveView.as_view(), name="add_leave"),
    path('edit_leave/<int:pk>', leave.EditLeaveView.as_view(), name="edit_leave"),
    path('delete_leave/<int:pk>', leave.DeleteLeaveView.as_view(), name="delete_leave"),

    # leave
    path('leavetypes/', leavetype.AllLeaveTypeView.as_view(), name="leavetypes"),
    path('leavetype/<int:pk>', leavetype.DetailLeaveTypeView.as_view(), name="leavetype"),
    path('add_leave_type/', leavetype.AddLeaveTypeView.as_view(), name="add_leave_type"),
    path('edit_leave_type/<int:pk>', leavetype.EditLeaveTypeView.as_view(), name="edit_leave_type"),
    path('delete_leave_type/<int:pk>', leavetype.DeleteLeaveTypeView.as_view(), name="delete_leave_type"),

]

correction/library/urls.py
from django.urls import path
from .views import author, publisher, subject, booklanguage, rack, book, studentbookissue, ebook, librarystudent

app_name = 'library'

urlpatterns = [
    # Author
    path('authors/', author.AllAuthorView.as_view(), name="authors"),
    path('author_detail/<int:pk>', author.DetailAuthorView.as_view(), name="author_detail"),
    path('add_author/', author.AddAuthorView.as_view(), name="add_author"),
    path('edit_author/<int:pk>', author.EditAuthorView.as_view(), name="edit_author"),
    path('delete_author/<int:pk>', author.DeleteAuthorView.as_view(), name="delete_author"),

    # Publisher
    path('publishers/', publisher.AllPublisherView.as_view(), name="publishers"),
    path('publisher/<int:pk>', publisher.DetailPublisherView.as_view(), name="publisher"),
    path('add_publisher/', publisher.AddPublisherView.as_view(), name="add_publisher"),
    path('edit_publisher/<int:pk>', publisher.EditPublisherView.as_view(), name="edit_publisher"),
    path('delete_publisher/<int:pk>', publisher.DeletePublisherView.as_view(), name="delete_publisher"),

    # Subject
    path('subjects/', subject.AllSubjectView.as_view(), name="subjects"),
    path('subject/<int:pk>', subject.DetailSubjectView.as_view(), name="subject"),
    path('add_subject/', subject.AddSubjectView.as_view(), name="add_subject"),
    path('edit_subject/<int:pk>', subject.EditSubjectView.as_view(), name="edit_subject"),
    path('delete_subject/<int:pk>', subject.DeleteSubjectView.as_view(), name="delete_subject"),

    # Book Language
    path('booklanguages/', booklanguage.AllBookLanguageView.as_view(), name="booklanguages"),
    path('booklanguage/<int:pk>', booklanguage.DetailBookLanguageView.as_view(), name="booklanguage"),
    path('add_booklanguage/', booklanguage.AddBookLanguageView.as_view(), name="add_booklanguage"),
    path('edit_booklanguage/<int:pk>', booklanguage.EditBookLanguageView.as_view(), name="edit_booklanguage"),
    path('delete_booklanguage/<int:pk>', booklanguage.DeleteBookLanguageView.as_view(), name="delete_booklanguage"),

    # Book Rack
    path('racks/', rack.AllRackView.as_view(), name="racks"),
    path('rack/<int:pk>', rack.DetailRackView.as_view(), name="rack"),
    path('add_rack/', rack.AddRackView.as_view(), name="add_rack"),
    path('edit_rack/<int:pk>', rack.EditRackView.as_view(), name="edit_rack"),
    path('delete_rack/<int:pk>', rack.DeleteRackView.as_view(), name="delete_rack"),

    # Book
    path('books/', book.AllBookView.as_view(), name="books"),
    path('book/<int:pk>', book.DetailBookView.as_view(), name="book"),
    path('add_book/', book.AddBookView.as_view(), name="add_book"),
    path('edit_book/<int:pk>', book.EditBookView.as_view(), name="edit_book"),
    path('delete_book/<int:pk>', book.DeleteBookView.as_view(), name="delete_book"),

    # E-Book
    path('ebooks/', ebook.AllEbookView.as_view(), name="ebooks"),
    path('ebook/<int:pk>', ebook.DetailEbookView.as_view(), name="ebook"),
    path('add_ebook/', ebook.AddEbookView.as_view(), name="add_ebook"),
    path('edit_ebook/<int:pk>', ebook.EditEbookView.as_view(), name="edit_ebook"),
    path('delete_ebook/<int:pk>', ebook.DeleteEbookView.as_view(), name="delete_ebook"),

    # Book
    path('bookissues/', studentbookissue.AllBookIssueView.as_view(), name="bookissues"),
    path('bookissue/<int:pk>', studentbookissue.DetailBookIssueView.as_view(), name="bookissue"),
    path('add_bookissue/', studentbookissue.AddBookIssueView.as_view(), name="add_bookissue"),
    path('add_student_bookissue/', studentbookissue.AddBookIssueView.as_view(), name="add_bookissue"),
    path('edit_bookissue/<int:pk>', studentbookissue.EditBookIssueView.as_view(), name="edit_bookissue"),
    path('delete_bookissue/<int:pk>', studentbookissue.DeleteBookIssueView.as_view(), name="delete_bookissue"),


    # Library student member
    # path('librarystudents/', librarystudent.AllLibraryStudentView.as_view(), name="librarystudents"),
    # path('librarystudent/<int:pk>', librarystudent.DetailLibraryStudentView.as_view(), name="librarystudent"),
    # path('add_librarystudent/', librarystudent.AddLibraryStudentView.as_view(), name="add_librarystudent"),
    # path('edit_librarystudent/', librarystudent.AddLibraryStudentView.as_view(), name="edit_librarystudent"),
    # path('delete_librarystudent/<int:pk>', librarystudent.DeleteLibraryStudentView.as_view(), name="delete_librarystudent"),

]

correction/library/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import mimetypes
import os


# Create your models here.


class Author(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True)
    image = models.ImageField(null=True, blank=True, upload_to='institute/institute/library/author')
    date_created = models.DateTimeField(auto_now_add=True)
    active_status = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return str(self.name)

    # ---------------------publisher------------------------------


class Publisher(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=200, null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to='institute/institute/library/author')
    date_created = models.DateTimeField(auto_now_add=True)
    active_status = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return self.name

    # ---------------------subject------------------------------


class Subject(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=200, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    active_status = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return str(self.name) if self.name else ''


# ---------------------book language------------------------------
class BookLanguage(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=200, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    active_status = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return self.name


# ---------------------rack number------------------------------
class Rack(models.Model):
    name = models.CharField(max_length=200)
    number = models.IntegerField(null=True, unique=True)
    date_created = models.DateTimeField(auto_now_add=True)
    active_status = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return self.name


# ---------------------book------------------------------
def validate_image(image):
    file_size = image.file.size
    limit_mb = 2
    if file_size > limit_mb * 1024 * 1024:
        raise ValidationError("Max size of file is %s KB" % limit_mb)


class Book(models.Model):
    title = models.CharField(max_length=200, null=True)
    book_number = models.CharField(max_length=200, null=True)
    isbn_number = models.CharField(max_length=200, null=True)
    price = models.FloatField(null=True)
    qty = models.IntegerField(null=True)
    publisher = models.ForeignKey(Publisher, null=True, on_delete=models.SET_NULL)
    author = models.ForeignKey(Author, null=True, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, null=True, on_delete=models.SET_NULL)
    book_language = models.ForeignKey(BookLanguage, null=True, on_delete=models.SET_NULL)
    rack = models.ForeignKey(Rack, null=True, on_delete=models.SET_NULL)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    status = models.IntegerField(default=0, null=True, blank=True)
    post_date = models.CharField(max_length=255, null=True, blank=True)
    active_status = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return str(self.title) if self.title else ''


# ---------------------e-book------------------------------
def validate_file(file):
    ext = os.path.splitext(file.name)[1]  # [0] returns path+filename
    valid_extensions = ['.pdf', '.doc', '.docx', '.jpg', '.png', '.ppt', '.pptx', '.text']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Please choose these  %s file type' % valid_extensions)
    file_size = file.file.size
    limit_mb = 250
    if file_size > limit_mb * 1024 * 1024:
        raise ValidationError("Max size of file is %s KB" % limit_mb)


class EBook(models.Model):
    title = models.CharField(max_length=200, null=True)
    book_number = models.CharField(max_length=200, null=True)
    isbn_number = models.CharField(max_length=200, null=True)
    price = models.FloatField(null=True)
    publisher = models.ForeignKey(Publisher, null=True, on_delete=models.SET_NULL)
    author = models.ForeignKey(Author, null=True, on_delete=models.SET_NULL)
    subject = models.ForeignKey(Subject, null=True, on_delete=models.SET_NULL)
    book_language = models.ForeignKey(BookLanguage, null=True, on_delete=models.SET_NULL)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True, validators=[validate_image])
    file = models.FileField(upload_to='ebook', null=True, validators=[validate_file])
    status = models.IntegerField(default=0, null=True, blank=True)
    post_date = models.CharField(max_length=255, null=True, blank=True)
    active_status = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return str(self.title)


# ---------------------book issue------------------------------

class BookIssue(models.Model):
    user_id = models.CharField(max_length=255, null=True)
    issued_by = models.ForeignKey(User, related_name='issued_by', null=True, on_delete=models.SET_NULL, blank=True)
    book = models.ForeignKey(Book, null=True, on_delete=models.SET_NULL)
    note = models.TextField(null=True, blank=True)
    status = models.IntegerField(default=0, null=True, blank=True)
    issue_date = models.CharField(max_length=255, null=True)
    return_date = models.CharField(max_length=255, null=True)
    active_status = models.IntegerField(null=True, blank=True, default=2)

    def __int__(self):
        return self.member


class LibraryStudentMember(models.Model):
    user_id = models.CharField(max_length=255, null=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.user_id

correction/library/forms/authorform.py
from bootstrap_datepicker_plus import DatePickerInput
from django import forms
from ..models import *


class AddAuthorForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AddAuthorForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = 'Enter text here ...'

    class Meta:
        model = Author
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={'rows': 5}),
        }


class EditAuthorForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EditAuthorForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = 'Enter text here ...'

    class Meta:
        model = Author
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={'rows': 5}),
        }

correction/library/forms/booklanguageform.py
from bootstrap_datepicker_plus import DatePickerInput
from django import forms
from ..models import *


class AddBookLanguageForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AddBookLanguageForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = 'Enter text here ...'

    class Meta:
        model = BookLanguage
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={'rows': 5}),
        }


class EditBookLanguageForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EditBookLanguageForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = 'Enter text here ...'

    class Meta:
        model = BookLanguage
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={'rows': 5}),
        }

correction/library/views/author.py
import datetime
from ..forms.authorform import AddAuthorForm, EditAuthorForm
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.utils import formats
from django.views import View
from ..models import Author


class AllAuthorView(View):
    model = Author
    template_name = 'author/index.html'

    def get(self, request):
        authors = Author.objects.filter(active_status=2).order_by('-id')
        date = formats.date_format(datetime.datetime.now().date(), 'd-m-Y')
        context = {'authors': authors, 'date': date}
        return render(request, self.template_name, context)


class AddAuthorView(View):
    model = Author
    form_class = AddAuthorForm
    template_name = 'author/add_author.html'

    def get(self, request):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            author = form.save(commit=False)
            author.save()
            response = {
                'user': author.pk,
                'success': 'Success! '
            }
            return JsonResponse(response)

        else:
            return JsonResponse({"error": form.errors}, json_dumps_params={'indent': 2})


class EditAuthorView(View):
    model = Author
    form_class = EditAuthorForm
    template_name = 'author/edit_author.html'

    def get(self, request, pk, *args, **kwargs):
        author = Author.objects.get(pk=pk)
        form = self.form_class(instance=author)
        context = {'form': form, 'pk': pk}
        return render(request, self.template_name, context)

    def post(self, request, pk, *args, **kwargs):
        authors = Author.objects.get(pk=pk)
        form = self.form_class(request.POST, request.FILES, instance=authors)

        if form.is_valid():
            form.save()

            response = {
                'success': 'Success! '
            }
            return JsonResponse(response)
        else:
            return JsonResponse({"error": form.errors}, json_dumps_params={'indent': 2})


class DeleteAuthorView(View):

    template_name = 'author/delete_author.html'

    def get(self, request, pk):
        author = Author.objects.get(pk=pk)
        context = {
            'author': author
        }
        return render(request, self.template_name, context)

    def post(self, request, pk, *args, **kwargs):
        author = Author.objects.get(pk=pk)
        author.active_status = 0
        author.save()
        return redirect('library:authors')


class DetailAuthorView(View):
    def get(self, request, pk):
        author = Author.objects.get(pk=pk)
        context = {
            'author': author
        }
        return render(request, 'author/detail_author.html', context)

correction/library/templates/bookissue/add_bookissue.html
{% extends 'account/base.html' %}
{% load static %}
{% block content %}
    {% if perms.library.add_bookissue %}
        <div class="fw fl mt40">
            <form action="" method="post" id="bookissue_form">
                <div class="alert alert-danger form_msg dn" ></div>
                <input type="text" value="" id="form_ed_id" class="dn">
                {% csrf_token %}
                {{ err_msg }}
                <div class="row">
                    <div class="col-md-6 mb15">
                        <label >{{ form.member.label }}</label>
                        {{ form.member }}
                    </div>

                    <div class="col-md-6 mb15">
                        <label >{{ form.issued_by.label }}</label>
                        {{ form.issued_by }}
                    </div>
                    <div class="col-md-6 mb15">
                        <label >{{ form.book.label }}</label>
                        {{ form.book }}
                    </div>

                    <div class="col-md-6 mb15">
                        <label >{{ form.status.label }}</label>
                        {{ form.status }}
                    </div>
                    <div class="col-md-6 mb15">
                        <label >{{ form.issue_date.label }}</label>
                        {{ form.issue_date }}
                    </div>
                    <div class="col-md-6 mb15">
                        <label >{{ form.return_date.label }}</label>
                        {{ form.return_date }}
                    </div>
                    <div class="col-md-6 mb15">
                        <label >{{ form.note.label }}</label>
                        {{ form.note }}
                    </div>
                </div>
				<input type="submit" value="Save" >
            </form>
        </div>
    {% endif %}
{% endblock %}

correction/library/templates/bookissue/delete_bookissue.html
{% extends 'account/base.html' %}
{% load static %}

{% block content %}

{% if perms.library.delete_bookissue %}
    <div class="fw fl mt40">
        <p>Are you sure?</p>
        <p>You want to delete {{bookissue.member}} ? </p>
        <a href="{% url 'library:bookissues' %}">Cancel</a>
        <form action="" method="post" id="">
        {% csrf_token %}
            <input type="submit" value="Confirm" class="btn btn-danger" >
        </form>
    </div>
{% endif %}

{% endblock %}

correction/library/templates/bookissue/edit_bookissue.html
{% extends 'account/base.html' %}
{% load static %}
{% block content %}
    {% if perms.library.edit_bookissue %}
        <div class="fw fl mt40">
            <form action="" method="post" id="bookissue_form">
                <div class="alert alert-danger form_msg dn" ></div>
                <input type="text" value="{{pk}}" id="form_ed_id" class="dn">
                {% csrf_token %}
                {{ err_msg }}
                <div class="row">
                    <div class="col-md-6 mb15">
                        <label >{{ form.member.label }}</label>
                        {{ form.member }}
                    </div>

                    <div class="col-md-6 mb15">
                        <label >{{ form.issued_by.label }}</label>
                        {{ form.issued_by }}
                    </div>
                    <div class="col-md-6 mb15">
                        <label >{{ form.book.label }}</label>
                        {{ form.book }}
                    </div>

                    <div class="col-md-6 mb15">
                        <label >{{ form.status.label }}</label>
                        {{ form.status }}
                    </div>
                    <div class="col-md-6 mb15">
                        <label >{{ form.issue_date.label }}</label>
                        {{ form.issue_date }}
                    </div>
                    <div class="col-md-6 mb15">
                        <label >{{ form.return_date.label }}</label>
                        {{ form.return_date }}
                    </div>
                    <div class="col-md-6 mb15">
                        <label >{{ form.note.label }}</label>
                        {{ form.note }}
                    </div>
                </div>
				<input type="submit" value="Save" >
            </form>
        </div>
    {% endif %}
{% endblock %}

correction/library/templates/bookissue/index.html
{% extends 'account/base.html' %}
{% load static %}

{% block content %}
{% if perms.library.view_bookissue   %}
{% if perms.library.add_bookissue %}
<div class="fw fl mt40">
    <a class="btn btn-secondary btn-sm" href="{% url 'library:add_bookissue' %}">Add  Student Book Issue</a>
</div>
{% endif %}
<div class="fw fl mt40">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">Serial No</th>
            <th scope="col">Issue By</th>
            <th scope="col">Book</th>
            <th scope="col">Issued for</th>
             {% if perms.library.change_bookissue %}
            <td>Edit</td>
            {% endif %}
            {% if perms.library.delete_bookissue %}
            <td>Delete</td>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for bookissue in bookissues %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td class="tcap">{{bookissue.issued_by}}</td>
            <td>{{bookissue.book}}</td>
            <td>{{bookissue.user_id}}</td>

            {% if perms.library.change_bookissue %}
            <td><a href="{% url 'library:edit_bookissue' bookissue.id %}" class="btn btn-primary btn-sm">Edit</a></td>
            {% endif %}
            {% if perms.library.delete_bookissue %}
            <td><a href="{% url 'library:delete_bookissue' bookissue.id %}" class="btn btn-danger btn-sm">Delete</a></td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endif %}

{% endblock %}