correction/correction/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('institute/', include('institute.urls')),
    path('frontoffice/', include('frontoffice.urls')),
    path('leave/', include('leave.urls')),
    path('library/', include('library.urls')),
    path('idcard/', include('idcard.urls')),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('admitcard/', include('admitcard.urls')),
    path('certificate/', include('certificate.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

correction/frontoffice/urls.py
from django.urls import path
from .views import complain, phonecalllog, postaldispatch, postalreceive, visitorbook

app_name = 'frontoffice'

urlpatterns = [
    # complain
    path('complains/', complain.AllComplainView.as_view(), name="complains"),
    path('complain/<int:pk>', complain.DetailComplainView.as_view(), name="complain"),
    path('add_complain/', complain.AddComplainView.as_view(), name="add_complain"),
    path('edit_complain/<int:pk>', complain.EditComplainView.as_view(), name="edit_complain"),
    path('delete_complain/<int:pk>', complain.DeleteComplainView.as_view(), name="delete_complain"),

    # complain
    path('phonecalllogs/', phonecalllog.AllPhoneCallLogView.as_view(), name="phonecalllogs"),
    path('phonecalllog/<int:pk>', phonecalllog.DetailPhoneCallLogView.as_view(), name="phonecalllog"),
    path('add_phonecalllog/', phonecalllog.AddPhoneCallLogView.as_view(), name="add_phonecalllog"),
    path('edit_phonecalllog/<int:pk>', phonecalllog.EditPhoneCallLogView.as_view(), name="edit_phonecalllog"),
    path('delete_phonecalllog/<int:pk>', phonecalllog.DeletePhoneCallLogView.as_view(), name="delete_phonecalllog"),

    #postaldispatch
    path('postaldispatchs/', postaldispatch.AllPostalDispatchView.as_view(), name="postaldispatchs"),
    path('postaldispatch/<int:pk>', postaldispatch.DetailPostalDispatchView.as_view(), name="postaldispatch"),
    path('add_postaldispatch/', postaldispatch.AddPostalDispatchView.as_view(), name="add_postaldispatch"),
    path('edit_postaldispatch/<int:pk>', postaldispatch.EditPostalDispatchView.as_view(), name="edit_postaldispatch"),
    path('delete_postaldispatch/<int:pk>', postaldispatch.DeletePostalDispatchView.as_view(), name="delete_postaldispatch"),

    #postalreceive
    path('postalreceives/', postalreceive.AllPostalReceiveView.as_view(), name="postalreceives"),
    path('postalreceive/<int:pk>', postalreceive.DetailPostalReceiveView.as_view(), name="postalreceive"),
    path('add_postalreceive/', postalreceive.AddPostalReceiveView.as_view(), name="add_postalreceive"),
    path('edit_postalreceive/<int:pk>', postalreceive.EditPostalReceiveView.as_view(), name="edit_postalreceive"),
    path('delete_postalreceive/<int:pk>', postalreceive.DeletePostalReceiveView.as_view(), name="delete_postalreceive"),

    # complain
    path('visitorbooks/', visitorbook.AllVisitorBookView.as_view(), name="visitorbooks"),
    path('visitorbook/<int:pk>', visitorbook.DetailVisitorBookView.as_view(), name="visitorbook"),
    path('add_visitorbook/', visitorbook.AddVisitorBookView.as_view(), name="add_visitorbook"),
    path('edit_visitorbook/<int:pk>', visitorbook.EditVisitorBookView.as_view(), name="edit_visitorbook"),
    path('delete_visitorbook/<int:pk>', visitorbook.DeleteVisitorBookView.as_view(),name="delete_visitorbook"),

]

correction/leave/urls.py
from django.urls import path
from .views import leavetype, leave

app_name = 'leave'

urlpatterns = [
    # leave
    path('leaves/', leave.AllLeaveView.as_view(), name="leaves"),
    path('leave/<int:pk>', leave.DetailLeaveView.as_view(), name="leave"),
    path('add_leave/', leave.AddLeaveView.as_view(), name="add_leave"),
    path('edit_leave/<int:pk>', leave.EditLeaveView.as_view(), name="edit_leave"),
    path('delete_leave/<int:pk>', leave.DeleteLeaveView.as_view(), name="delete_leave"),

    # leave
    path('leavetypes/', leavetype.AllLeaveTypeView.as_view(), name="leavetypes"),
    path('leavetype/<int:pk>', leavetype.DetailLeaveTypeView.as_view(), name="leavetype"),
    path('add_leave_type/', leavetype.AddLeaveTypeView.as_view(), name="add_leave_type"),
    path('edit_leave_type/<int:pk>', leavetype.EditLeaveTypeView.as_view(), name="edit_leave_type"),
    path('delete_leave_type/<int:pk>', leavetype.DeleteLeaveTypeView.as_view(), name="delete_leave_type"),

]

correction/frontoffice/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.core.exceptions import ValidationError
import os
from .choices import CALL_TYPE, TYPE, choice_status


def validate_image(image):
    file_size = image.file.size
    limit_mb = 2
    if file_size > limit_mb * 1024 * 1024:
        raise ValidationError("Max size of file is %s KB" % limit_mb)


def validate_file(file):
    ext = os.path.splitext(file.name)[1]  # [0] returns path+filename
    valid_extensions = ['.pdf','.doc', '.docx', '.jpg', '.png', '.ppt', '.pptx', '.text']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Please choose these  %s file type' % valid_extensions)
    file_size = file.file.size
    limit_mb = 250
    if file_size > limit_mb * 1024 * 1024:
        raise ValidationError("Max size of file is %s KB" % limit_mb)


class Visitorbook(models.Model):
    purpose = models.CharField(max_length=200, null=True)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    meet_user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    id_card = models.CharField(max_length=200, null=True)
    date = models.CharField(max_length=255, null=True)
    in_time = models.CharField(max_length=255, null=True)
    out_time = models.CharField(max_length=255, null=True, blank=True)
    note = models.TextField(null=True,blank=True)
    attachment = models.FileField(upload_to='visitorbook', null=True, blank=True, validators=[validate_file])
    date_created = models.DateTimeField(auto_now_add=True)
    active_status = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return self.name


class Phonecalllog(models.Model):
    name=models.CharField(max_length=200, null=True )
    phone=models.CharField(max_length=200, null=True )
    call_duration=models.CharField(max_length=200, null=True )
    date=models.CharField(max_length=255, null=True)
    followup=models.CharField(max_length=255, null=True, blank=True)
    call_type=models.IntegerField(null=True, choices=CALL_TYPE)
    description=models.TextField(null=True,blank=True)
    note=models.TextField(null=True,blank=True)
    date_created=models.DateTimeField(auto_now_add=True)
    active_status = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return self.name


class Postaldispatch(models.Model):
    receiver=models.CharField(max_length=200, null=True )
    sender=models.CharField(max_length=200, null=True )
    referance=models.CharField(max_length=200, null=True )
    dispatch_date=models.CharField(max_length=255, null=True)
    address=models.TextField(null=True)
    note=models.TextField(null=True,blank=True)
    attachment=models.FileField(upload_to='postal', null=True, blank=True,validators=[validate_file])
    date_created=models.DateTimeField(auto_now_add=True)
    active_status = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return self.receiver


class Postalreceive(models.Model):
    receiver=models.CharField(max_length=200, null=True )
    sender=models.CharField(max_length=200, null=True )
    referance=models.CharField(max_length=200, null=True )
    receive_date=models.CharField(max_length=255, null=True)
    address=models.TextField(null=True)
    note=models.TextField(null=True,blank=True)
    attachment=models.FileField(upload_to='postal', null=True, blank=True,validators=[validate_file])
    date_created=models.DateTimeField(auto_now_add=True)
    active_status = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return self.receiver


class Complain(models.Model):

    complain_type=models.CharField(max_length=100, null=True, choices=TYPE)
    complain_by=models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    phone=models.CharField(max_length=200, null=True)
    date=models.CharField(max_length=255, null=True)
    description=models.TextField(null=True,blank=True)
    action_taken=models.TextField(null=True,blank=True)
    assigned=models.ForeignKey(User , null=True, on_delete=models.SET_NULL, related_name='assigned')
    note=models.TextField(null=True,blank=True)
    attachment=models.FileField(upload_to='postal', null=True, blank=True,validators=[validate_file])
    date_created=models.DateTimeField(auto_now_add=True)
    active_status = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return self.complain_type

correction/frontoffice/views/complain.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.generic import View
from ..models import Complain
from ..forms.complainform import AddComplainForm, EditComplainForm
import datetime
from django.utils import formats


class AllComplainView(View):
    model = Complain
    template_name = 'complain/index.html'

    def get(self, request):
        complains = Complain.objects.filter(active_status=2).order_by('-id')
        date = formats.date_format(datetime.datetime.now().date(), 'd-m-Y')
        context = {'complains': complains, 'date': date}
        return render(request, self.template_name, context)


class AddComplainView(View):
    model = Complain
    form_class = AddComplainForm
    template_name = 'complain/add_complain.html'

    def get(self, request):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request,*args, **kwargs):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():
            conplain = form.save(commit=False)
            conplain.save()

            response = {
                'user': conplain.pk,
                'success': 'Success! '
            }
            return JsonResponse(response)

        else:
            return JsonResponse({"error": form.errors}, json_dumps_params={'indent': 2})


class EditComplainView(View):
    model = Complain
    form_class = EditComplainForm
    template_name = 'complain/edit_complain.html'

    def get(self, request, pk, *args, **kwargs):
        complain = Complain.objects.get(pk=pk)
        form = self.form_class(instance=complain)
        context = {'form': form, 'pk': pk}
        return render(request, self.template_name, context)

    def post(self, request, pk, *args, **kwargs):
        complain = Complain.objects.get(pk=pk)
        form = self.form_class(request.POST,request.FILES, instance=complain)

        if form.is_valid():
            form.save()

            response = {
                'success': 'Success! '
            }
            return JsonResponse(response)

        else:
            return JsonResponse({"error": form.errors}, json_dumps_params={'indent': 2})


class DeleteComplainView(View):

    template_name = 'complain/delete_complain.html'

    def get(self, request, pk):
        complain = Complain.objects.get(pk=pk)
        context ={
            'complain': complain
        }
        return render(request, self.template_name,context)

    def post(self, request, pk, *args, **kwargs):
        notice = Complain.objects.get(pk=pk)
        notice.active_status = 0
        notice.save()

        return redirect('frontoffice:complains')


class DetailComplainView(View):
    pass

correction/frontoffice/views/phonecalllog.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.generic import View
from ..models import Phonecalllog
from ..forms.phonecalllogform import AddPhonecalllogForm, EditPhonecalllogForm


class AllPhoneCallLogView(View):
    model = Phonecalllog
    template_name = 'phonecalllog/index.html'

    def get(self, request):
        phonecalllogs = Phonecalllog.objects.filter(active_status=2).order_by('-id')
        context = {'phonecalllogs': phonecalllogs}
        return render(request, self.template_name, context)


class AddPhoneCallLogView(View):
    model = Phonecalllog
    form_class = AddPhonecalllogForm
    template_name = 'phonecalllog/add_phonecalllog.html'

    def get(self, request):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            phonecalllog = form.save(commit=False)
            phonecalllog.save()

            response = {
                'user': phonecalllog.pk,
                'success': 'Success! '
            }
            return JsonResponse(response)

        else:
            return JsonResponse({"error": form.errors}, json_dumps_params={'indent': 2})


class EditPhoneCallLogView(View):
    model = Phonecalllog
    form_class = EditPhonecalllogForm
    template_name = 'phonecalllog/edit_phonecalllog.html'

    def get(self, request, pk, *args, **kwargs):
        phonecalllog = Phonecalllog.objects.get(pk=pk)
        form = self.form_class(instance=phonecalllog)
        context = {'form': form, 'pk': pk}
        return render(request, self.template_name, context)

    def post(self, request, pk, *args, **kwargs):
        phonecalllog = Phonecalllog.objects.get(pk=pk)
        form = self.form_class(request.POST, request.FILES, instance=phonecalllog)

        if form.is_valid():
            form.save()
            response = {
                'success': 'Success! '
            }
            return JsonResponse(response)

        else:
            return JsonResponse({"error": form.errors}, json_dumps_params={'indent': 2})


class DeletePhoneCallLogView(View):

    template_name = 'phonecalllog/delete_phonecalllog.html'

    def get(self, request, pk):
        phonecalllog = Phonecalllog.objects.get(pk=pk)
        context = {
            'phonecalllog': phonecalllog
        }
        return render(request, self.template_name,context)

    def post(self, request, pk, *args, **kwargs):
        phonecalllog = Phonecalllog.objects.get(pk=pk)
        phonecalllog.active_status = 0
        phonecalllog.save()

        return redirect('frontoffice:phonecalllogs')


class DetailPhoneCallLogView(View):
   pass

correction/frontoffice/views/visitorbook.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.generic import View
from ..models import Visitorbook
from ..forms.visitorbookform import AddVisitorbookForm, EditVisitorbookForm
import datetime
from django.utils import formats


class AllVisitorBookView(View):
    model = Visitorbook
    template_name = 'visitorbook/index.html'

    def get(self, request):
        visitorbooks = Visitorbook.objects.filter(active_status=2).order_by('-id')
        date = formats.date_format(datetime.datetime.now().date(), 'd-m-Y')
        context = {'visitorbooks': visitorbooks, 'date': date}
        return render(request, self.template_name, context)


class AddVisitorBookView(View):
    model = Visitorbook
    form_class = AddVisitorbookForm
    template_name = 'visitorbook/add_visitorbook.html'

    def get(self, request):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request,*args, **kwargs):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():
            visitorbook = form.save(commit=False)
            visitorbook.save()
            response = {
                'user': visitorbook.pk,
                'success': 'Success! '
            }
            return JsonResponse(response)
        else:
            return JsonResponse({"error": form.errors}, json_dumps_params={'indent': 2})


class EditVisitorBookView(View):
    model = Visitorbook
    form_class = EditVisitorbookForm
    template_name = 'visitorbook/edit_visitorbook.html'

    def get(self, request, pk, *args, **kwargs):
        visitorbook = Visitorbook.objects.get(pk=pk)
        form = self.form_class(instance=visitorbook)
        context = {'form': form, 'pk': pk}
        return render(request, self.template_name, context)

    def post(self, request, pk, *args, **kwargs):
        visitorbook = Visitorbook.objects.get(pk=pk)
        form = self.form_class(request.POST, request.FILES, instance=visitorbook)

        if form.is_valid():
            form.save()
            response = {
                'success': 'Success! '
            }
            return JsonResponse(response)
        else:
            return JsonResponse({"error": form.errors}, json_dumps_params={'indent': 2})


class DeleteVisitorBookView(View):
    template_name = 'visitorbook/delete_visitorbook.html'

    def get(self, request, pk):
        visitorbook = Visitorbook.objects.get(pk=pk)
        context = {
            'visitorbook': visitorbook
        }
        return render(request, self.template_name, context)

    def post(self, request, pk, *args, **kwargs):
        visitorbook = Visitorbook.objects.get(pk=pk)
        visitorbook.active_status = 0
        visitorbook.save()
        return redirect('frontoffice:visitorbooks')


class DetailVisitorBookView(View):
    pass

correction/frontoffice/templates/postalreceive/add_postal_receive.html
{% extends 'account/base.html' %}
{% load static %}
{% block content %}
    {% if perms.frontoffice.add_postalreceive  %}
        <div class="fw fl mt40">
            <form action="" method="post" id="postal_receive_form" novalidate>
                <div class="alert alert-danger form_msg dn" ></div>
                <input type="text" value="" id="form_ed_id" class="dn">
                {% csrf_token %}
                {{ err_msg }}
                <div class="row">
                    <div class="col-md-3 mb15">
                        <label >{{ form.receiver.label }}</label>
                        {{ form.receiver }}
                    </div>

                    <div class="col-md-3 mb15">
                        <label >{{ form.sender.label }}</label>
                        {{ form.sender }}
                    </div>
                    <div class="col-md-3 mb15">
                        <label >{{ form.referance.label }}</label>
                        {{ form.referance }}
                    </div>

                    <div class="col-md-3 mb15">
                        <label >{{ form.receive_date.label }}</label>
                        {{ form.receive_date }}
                    </div>

                    <div class="col-md-12 mb15">
                        <label >{{ form.address.label }}</label>
                        {{ form.address }}
                    </div>

                    <div class="col-md-12 mb15">
                        <label >{{ form.note.label }}</label>
                        {{ form.note }}
                    </div>
                    <div class="col-md-12 mb15">
                        <label >{{ form.attachment.label }}</label>
                        {{ form.attachment }}
                    </div>
                    <div class="col-md-12 mb15">
                        <label >{{ form.assigned.label }}</label>
                        {{ form.assigned }}
                    </div>
                </div>
				<input type="submit" value="Save" >
            </form>
        </div>
    {% endif %}
<!--<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>-->
{% endblock %}

correction/frontoffice/templates/postalreceive/add_postalreceive.html
{% extends 'account/base.html' %}
{% load static %}
{% block content %}
    {% if perms.frontoffice.add_postalreceive  %}
        <div class="fw fl mt40">
            <form action="" method="post" id="postal_receive_form" novalidate>
                <div class="alert alert-danger form_msg dn" ></div>
                <input type="text" value="" id="form_ed_id" class="dn">
                {% csrf_token %}
                {{ err_msg }}
                <div class="row">
                    <div class="col-md-3 mb15">
                        <label >{{ form.receiver.label }}</label>
                        {{ form.receiver }}
                    </div>

                    <div class="col-md-3 mb15">
                        <label >{{ form.sender.label }}</label>
                        {{ form.sender }}
                    </div>
                    <div class="col-md-3 mb15">
                        <label >{{ form.referance.label }}</label>
                        {{ form.referance }}
                    </div>

                    <div class="col-md-3 mb15">
                        <label >{{ form.receive_date.label }}</label>
                        {{ form.receive_date }}
                    </div>

                    <div class="col-md-12 mb15">
                        <label >{{ form.address.label }}</label>
                        {{ form.address }}
                    </div>

                    <div class="col-md-12 mb15">
                        <label >{{ form.note.label }}</label>
                        {{ form.note }}
                    </div>
                    <div class="col-md-12 mb15">
                        <label >{{ form.attachment.label }}</label>
                        {{ form.attachment }}
                    </div>
                    <div class="col-md-12 mb15">
                        <label >{{ form.assigned.label }}</label>
                        {{ form.assigned }}
                    </div>
                </div>
				<input type="submit" value="Save" >
            </form>
        </div>
    {% endif %}
<!--<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>-->
{% endblock %}

correction/frontoffice/templates/postalreceive/delete_postalreceive.html
{% extends 'account/base.html' %}
{% load static %}

{% block content %}

{% if perms.frontoffice.delete_postalreceive %}
    <div class="fw fl mt40">
        <p>Are you sure?</p>
        <p>You want to delete  {{postalreceive.receiver}} ?</p>
        <a href="{% url 'frontoffice:postalreceives' %}">Cancel</a>
        <form action="" method="post" id="">
        {% csrf_token %}
            <input type="submit" value="Confirm" class="btn btn-danger" >
        </form>
    </div>
{% endif %}

{% endblock %}

correction/frontoffice/templates/postalreceive/edit_postal_receive.html
{% extends 'account/base.html' %}
{% load static %}
{% block content %}
    {% if perms.frontoffice.add_postalreceive  %}
        <div class="fw fl mt40">
            <form action="" method="post" id="postal_receive_form" novalidate>
                <div class="alert alert-danger form_msg dn" ></div>
                <input type="text" value="{{ pk }}" id="form_ed_id" class="dn">
                {% csrf_token %}
                {{ err_msg }}
                <div class="row">
                    <div class="col-md-3 mb15">
                        <label >{{ form.receiver.label }}</label>
                        {{ form.receiver }}
                    </div>

                    <div class="col-md-3 mb15">
                        <label >{{ form.sender.label }}</label>
                        {{ form.sender }}
                    </div>
                    <div class="col-md-3 mb15">
                        <label >{{ form.referance.label }}</label>
                        {{ form.referance }}
                    </div>

                    <div class="col-md-3 mb15">
                        <label >{{ form.receive_date.label }}</label>
                        {{ form.receive_date }}
                    </div>

                    <div class="col-md-12 mb15">
                        <label >{{ form.address.label }}</label>
                        {{ form.address }}
                    </div>

                    <div class="col-md-12 mb15">
                        <label >{{ form.note.label }}</label>
                        {{ form.note }}
                    </div>
                    <div class="col-md-12 mb15">
                        <label >{{ form.attachment.label }}</label>
                        {{ form.attachment }}
                    </div>
                    <div class="col-md-12 mb15">
                        <label >{{ form.assigned.label }}</label>
                        {{ form.assigned }}
                    </div>
                </div>
				<input type="submit" value="Save" >
            </form>
        </div>
    {% endif %}
<!--<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>-->
{% endblock %}

correction/frontoffice/templates/postalreceive/edit_postalreceive.html
{% extends 'account/base.html' %}
{% load static %}
{% block content %}
    {% if perms.frontoffice.add_postalreceive  %}
        <div class="fw fl mt40">
            <form action="" method="post" id="postal_receive_form" novalidate>
                <div class="alert alert-danger form_msg dn" ></div>
                <input type="text" value="{{ pk }}" id="form_ed_id" class="dn">
                {% csrf_token %}
                {{ err_msg }}
                <div class="row">
                    <div class="col-md-3 mb15">
                        <label >{{ form.receiver.label }}</label>
                        {{ form.receiver }}
                    </div>

                    <div class="col-md-3 mb15">
                        <label >{{ form.sender.label }}</label>
                        {{ form.sender }}
                    </div>
                    <div class="col-md-3 mb15">
                        <label >{{ form.referance.label }}</label>
                        {{ form.referance }}
                    </div>

                    <div class="col-md-3 mb15">
                        <label >{{ form.receive_date.label }}</label>
                        {{ form.receive_date }}
                    </div>

                    <div class="col-md-12 mb15">
                        <label >{{ form.address.label }}</label>
                        {{ form.address }}
                    </div>

                    <div class="col-md-12 mb15">
                        <label >{{ form.note.label }}</label>
                        {{ form.note }}
                    </div>
                    <div class="col-md-12 mb15">
                        <label >{{ form.attachment.label }}</label>
                        {{ form.attachment }}
                    </div>
                    <div class="col-md-12 mb15">
                        <label >{{ form.assigned.label }}</label>
                        {{ form.assigned }}
                    </div>
                </div>
				<input type="submit" value="Save" >
            </form>
        </div>
    {% endif %}
<!--<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>-->
{% endblock %}

correction/frontoffice/templates/postalreceive/index.html
{% extends 'account/base.html' %}
{% block content %}
    {% if perms.frontoffice.view_postalreceive  %}

        {% if perms.frontoffice.add_postalreceive   %}
            <div class="fw fl mt40">
                <a  class="btn btn-secondary btn-sm" href="{% url 'frontoffice:add_postalreceive' %}">Add Postal Receive</a>
            </div>
        {% endif %}

        <div class="fw fl mt40">
            <table class="table table-hover">
                <thead>
				<tr>
					<th>Serial</th>
					<th>Receiver</th>
					<th>Sender</th>
					<th>Reference</th>
					<th>Receive Date</th>
					<th>Address</th>
					<th>Attachment</th>
                        {% if perms.frontoffice.change_postalreceive    %}
                            <th scope="col">Edit</th>
                        {% endif %}
                        {% if perms.frontoffice.delete_postalreceive  %}
                            <th scope="col">Delete</th>
                        {% endif %}
				</tr>
                </thead>
            <tbody>

            {% for postalreceive in postalreceives  %}
                <tr>
					<td>{{forloop.counter}}</td>
					<td>{{postalreceive.receiver}}</td>
					<td >{{postalreceive.sender}}</td>
					<td>{{postalreceive.referance}}</td>
					<td>{{postalreceive.receive_date}}</td>
					<td>{{postalreceive.address}}</td>
					<td>
						{% if postalreceive.attachment %}
							<a class="badge badge-info" href="{{postalreceive.attachment.url}}" target="_blank">Attachment</a>
						{% else %}
							None
						{% endif %}
					</td>


                    {% if perms.frontoffice.change_postalreceive %}
                        <td><a href="{% url 'frontoffice:edit_postalreceive' postalreceive.id %}" class="btn btn-primary btn-sm">Edit</a></td>
                    {% endif %}
                    {% if perms.frontoffice.delete_postalreceive  %}
                        <td><a href="{% url 'frontoffice:delete_postalreceive' postalreceive.id %}" class="btn btn-danger btn-sm">Delete</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
    {% endif %}
{% endblock content %}